### ISSUE TITLE
New todo sentence breaking at white space

### ISSUE THREAD

**Issue by unclebay143** [Whoistolu/To-Do-List#14]
1. New entry

![image](https://user-images.githubusercontent.com/58919619/138356213-f5bf07de-2033-4511-a947-8e83f60365cd.png)

2. Only the first word is rendered in the UI

![image](https://user-images.githubusercontent.com/58919619/138356345-c25dec8b-36c8-46df-8211-91110c750662.png)

3. But the local storage has the full data

![image](https://user-images.githubusercontent.com/58919619/138356538-6f8aa078-7fc2-473c-b785-91b916a2a4ae.png)

4. Bug: the `input` attribute should have a quote `value="value=${item.description} "`
![image](https://user-images.githubusercontent.com/58919619/138356832-a9c10c53-11c7-44c4-8796-51a4119edb04.png)

5. Fixed: all works fine now
![image](https://user-images.githubusercontent.com/58919619/138357025-42c50548-b8e0-4c77-8d30-286789846bbd.png)

will send in a pull request soon!!!

**Comment by Whoistolu** [comment]
### Hello @unclebay143,
Thank you for your observation and suggested changes.
- However, the sent-in pull request does not pass the `Linters Configuration` tests, kindly fix the errors going forward.

**Comment by unclebay143** [comment]
just noticed that, will look them up and send in another PR to fix that. my Eslint uses double quotes, will reconfigure it.
